export type University = {
  id: string;
  name: string;
  shortName: string;
  location: string;
  type: string;
  majorsCount: number;
  ranking: number;
  rating: number;
  color: string;
  icon: string;
  website: string;
  tuitionRange: string;
  tuitionNote: string;
}

export type Major = {
  id: string;
  name: string;
  schoolId: string;
  schoolName: string;
  examGroups: string[];
  score: number;
  tuitionFee: number; // in million VND/year
  demand: number;
  salary: string;
  views: number;
  color: string;
  icon: string;
  duration: number; // in years
  students: number;
  category: string;
  description?: string;
  suggestedJobs?: string[];
  code: string;
}

export const mockUniversities: University[] = [
  {
    id: 'DUT',
    name: 'Đại học Bách khoa - Đại học Đà Nẵng',
    shortName: 'DUT',
    location: 'Đà Nẵng',
    type: 'Công lập',
    majorsCount: 42,
    ranking: 1,
    rating: 4.8,
    color: 'bg-red-600',
    icon: '⚙️',
    website: 'https://dut.udn.vn',
    tuitionRange: '22 - 28 triệu/năm',
    tuitionNote: 'Tăng tối đa 10% mỗi năm theo quy định của nhà nước.',
  },
  {
    id: 'DUE',
    name: 'Đại học Kinh tế - Đại học Đà Nẵng',
    shortName: 'DUE',
    location: 'Đà Nẵng',
    type: 'Công lập',
    majorsCount: 35,
    ranking: 2,
    rating: 4.7,
    color: 'bg-green-600',
    icon: '💼',
    website: 'https://due.udn.vn',
    tuitionRange: '20 - 25 triệu/năm',
    tuitionNote: 'Học phí các chương trình chất lượng cao khoảng 35 triệu/năm.',
  },
  {
    id: 'UFLS',
    name: 'Đại học Ngoại ngữ - Đại học Đà Nẵng',
    shortName: 'UFLS',
    location: 'Đà Nẵng',
    type: 'Công lập',
    majorsCount: 22,
    ranking: 3,
    rating: 4.6,
    color: 'bg-blue-600',
    icon: '🌍',
    website: 'https://ufl.udn.vn',
    tuitionRange: '15 - 20 triệu/năm',
    tuitionNote: 'Mức học phí tùy thuộc vào ngành ngôn ngữ chuyên sâu.',
  },
  {
    id: 'UED',
    name: 'Đại học Sư phạm - Đại học Đà Nẵng',
    shortName: 'UED',
    location: 'Đà Nẵng',
    type: 'Công lập',
    majorsCount: 45,
    ranking: 4,
    rating: 4.5,
    color: 'bg-purple-600',
    icon: '👩‍🏫',
    website: 'https://ued.udn.vn',
    tuitionRange: 'Miễn học phí (Ngành SP)',
    tuitionNote: 'Các ngành cử nhân ngoài sư phạm thu học phí từ 15-18 triệu/năm.',
  },
  {
    id: 'UTE',
    name: 'Đại học Sư phạm Kỹ thuật - Đại học Đà Nẵng',
    shortName: 'UTE',
    location: 'Đà Nẵng',
    type: 'Công lập',
    majorsCount: 20,
    ranking: 5,
    rating: 4.5,
    color: 'bg-indigo-600',
    icon: '🔧',
    website: 'https://ute.udn.vn',
    tuitionRange: '18 - 22 triệu/năm',
    tuitionNote: 'Các ngành kỹ thuật thực hành có phụ phí nguyên vật liệu nhỏ.',
  },
  {
    id: 'VKU',
    name: 'Đại học CNTT và Truyền thông Việt - Hàn',
    shortName: 'VKU',
    location: 'Đà Nẵng',
    type: 'Công lập',
    majorsCount: 18,
    ranking: 6,
    rating: 4.6,
    color: 'bg-cyan-600',
    icon: '🖥️',
    website: 'https://vku.udn.vn',
    tuitionRange: '14 - 16 triệu/năm',
    tuitionNote: 'Mức học phí ưu đãi nhờ sự hỗ trợ từ chính phủ Hàn Quốc.',
  },
  {
    id: 'DTU',
    name: 'Đại học Duy Tân',
    shortName: 'DTU',
    location: 'Đà Nẵng',
    type: 'Tư thục',
    majorsCount: 50,
    ranking: 7,
    rating: 4.4,
    color: 'bg-orange-600',
    icon: '🏫',
    website: 'https://duytan.edu.vn',
    tuitionRange: '25 - 45 triệu/năm',
    tuitionNote: 'Các chương trình tiên tiến/liên kết quốc tế từ 50-80 triệu/năm.',
  },
  {
    id: 'FPT',
    name: 'Đại học FPT Đà Nẵng',
    shortName: 'FPT',
    location: 'Đà Nẵng',
    type: 'Tư thục',
    majorsCount: 15,
    ranking: 8,
    rating: 4.6,
    color: 'bg-orange-500',
    icon: '💻',
    website: 'https://dnuni.fpt.edu.vn',
    tuitionRange: '80 - 100 triệu/năm',
    tuitionNote: 'Đã bao gồm chi phí giáo trình và các kỳ thực tập OJT doanh nghiệp.',
  },
  {
    id: 'UDA',
    name: 'Đại học Đông Á',
    shortName: 'UDA',
    location: 'Đà Nẵng',
    type: 'Tư thục',
    majorsCount: 30,
    ranking: 9,
    rating: 4.3,
    color: 'bg-rose-500',
    icon: '🌸',
    website: 'https://donga.edu.vn',
    tuitionRange: '20 - 30 triệu/năm',
    tuitionNote: 'Cam kết không tăng học phí trong suốt toàn khóa học.',
  },
  {
    id: 'DAU',
    name: 'Đại học Kiến trúc Đà Nẵng',
    shortName: 'DAU',
    location: 'Đà Nẵng',
    type: 'Tư thục',
    majorsCount: 25,
    ranking: 10,
    rating: 4.2,
    color: 'bg-yellow-600',
    icon: '🏛️',
    website: 'https://dau.edu.vn',
    tuitionRange: '25 - 35 triệu/năm',
    tuitionNote: 'Học phí ngành kiến trúc và thiết kế thường cao hơn các ngành kinh tế.',
  },
]

export const mockMajors: Major[] = [
  {
    id: '1',
    name: 'Khoa học máy tính',
    schoolId: 'DUT',
    schoolName: 'Đại học Bách khoa - Đại học Đà Nẵng',
    examGroups: ['A00', 'A01'],
    score: 25.5,
    tuitionFee: 25,
    demand: 4.8,
    salary: '20-40M',
    views: 15200,
    color: 'bg-blue-100',
    icon: '💻',
    duration: 4,
    students: 350,
    category: 'tech',
    code: '7480101',
    description: 'Ngành học chuyên nghiên cứu về cơ sở lý thuyết của thông tin và tính toán cùng sự thực hiện và ứng dụng của chúng trong các hệ thống máy tính.',
    suggestedJobs: ['Lập trình viên (Developer)', 'Kỹ sư phần mềm', 'Chuyên viên phân tích dữ liệu', 'Kỹ sư AI/Machine Learning']
  },
  {
    id: '2',
    name: 'Kỹ thuật phần mềm',
    schoolId: 'FPT',
    schoolName: 'Đại học FPT Đà Nẵng',
    examGroups: ['A00', 'A01', 'D01'],
    score: 23.0,
    tuitionFee: 80,
    demand: 4.9,
    salary: '22-38M',
    views: 12100,
    color: 'bg-purple-100',
    icon: '⚙️',
    duration: 4,
    students: 600,
    category: 'tech',
    code: '7480103',
    description: 'Chuyên ngành đào tạo các kiến thức về quy trình, phương pháp và công cụ để xây dựng, phát triển và bảo trì phần mềm một cách chuyên nghiệp.',
    suggestedJobs: ['Kỹ sư phần mềm', 'Chuyên viên kiểm thử phần mềm (QA/QC)', 'Quản trị dự án CNTT', 'Kỹ sư hệ thống']
  },
  {
    id: '3',
    name: 'Quản trị kinh doanh',
    schoolId: 'DUE',
    schoolName: 'Đại học Kinh tế - Đại học Đà Nẵng',
    examGroups: ['A00', 'A01', 'D01', 'D07'],
    score: 24.5,
    tuitionFee: 22,
    demand: 4.2,
    salary: '15-30M',
    views: 9800,
    color: 'bg-green-100',
    icon: '📊',
    duration: 4,
    students: 800,
    category: 'business',
    code: '7340101',
    description: 'Ngành học cung cấp các kiến thức toàn diện về quản trị, từ tài chính, nhân sự, marketing đến chiến lược kinh doanh nhằm điều hành một tổ chức/doanh nghiệp hiệu quả.',
    suggestedJobs: ['Chuyên viên phòng kế hoạch', 'Quản lý nhân sự', 'Chuyên viên phát triển kinh doanh', 'Giám đốc điều hành (CEO)']
  },
  {
    id: '4',
    name: 'Ngôn ngữ Anh',
    schoolId: 'UFLS',
    schoolName: 'Đại học Ngoại ngữ - Đại học Đà Nẵng',
    examGroups: ['D01', 'D14', 'D15'],
    score: 23.8,
    tuitionFee: 18,
    demand: 4.5,
    salary: '12-25M',
    views: 8500,
    color: 'bg-pink-100',
    icon: '🇬🇧',
    duration: 4,
    students: 450,
    category: 'language',
    code: '7220201',
    description: 'Đào tạo chuyên sâu về ngôn ngữ, văn hóa, văn học các nước nói tiếng Anh, đồng thời trang bị kỹ năng giao tiếp và làm việc trong môi trường quốc tế.',
    suggestedJobs: ['Biên phiên dịch viên', 'Chuyên viên đối ngoại', 'Giáo viên tiếng Anh', 'Hướng dẫn viên du lịch quốc tế']
  },
  {
    id: '5',
    name: 'Sư phạm Tiếng Anh',
    schoolId: 'UED',
    schoolName: 'Đại học Sư phạm - Đại học Đà Nẵng',
    examGroups: ['D01', 'D14', 'D15'],
    score: 26.0,
    tuitionFee: 0,
    demand: 4.0,
    salary: '10-20M',
    views: 7300,
    color: 'bg-yellow-100',
    icon: '👩‍🏫',
    duration: 4,
    students: 200,
    category: 'education',
    code: '7140231',
    description: 'Ngành học kết hợp giữa kiến thức chuyên sâu về tiếng Anh và nghiệp vụ sư phạm để giảng dạy tiếng Anh tại các trường học hoặc trung tâm ngoại ngữ.',
    suggestedJobs: ['Giáo viên tiếng Anh THCS/THPT', 'Giảng viên đại học', 'Chuyên gia xây dựng chương trình học', 'Tác giả sách giáo khoa']
  },
  {
    id: '6',
    name: 'Marketing',
    schoolId: 'DUE',
    schoolName: 'Đại học Kinh tế - Đại học Đà Nẵng',
    examGroups: ['A00', 'A01', 'D01'],
    score: 26.5,
    tuitionFee: 22,
    demand: 4.7,
    salary: '15-35M',
    views: 11000,
    color: 'bg-orange-100',
    icon: '📱',
    duration: 4,
    students: 400,
    category: 'business',
    code: '7340115',
    description: 'Cung cấp kiến thức về nghiên cứu thị trường, hành vi người tiêu dùng, xây dựng thương hiệu, quảng cáo và truyền thông kỹ thuật số.',
    suggestedJobs: ['Chuyên viên marketing digital', 'Chuyên gia PR', 'Quản lý thương hiệu (Brand Manager)', 'Nhà phân tích thị trường']
  },
  {
    id: '7',
    name: 'An toàn thông tin',
    schoolId: 'DTU',
    schoolName: 'Đại học Duy Tân',
    examGroups: ['A00', 'A01'],
    score: 21.0,
    tuitionFee: 35,
    demand: 4.6,
    salary: '25-45M',
    views: 6500,
    color: 'bg-cyan-100',
    icon: '🔒',
    duration: 4,
    students: 150,
    category: 'tech',
    code: '7480202',
    description: 'Trang bị kỹ năng bảo vệ hệ thống mạng, dữ liệu khỏi các cuộc tấn công mạng, đồng thời có khả năng phân tích và phản ứng trước các rủi ro bảo mật.',
    suggestedJobs: ['Chuyên viên bảo mật hệ thống', 'Kỹ sư an ninh mạng', 'Chuyên gia kiểm thử xâm nhập (Pen-tester)', 'Tư vấn an toàn thông tin']
  },
  {
    id: '8',
    name: 'Du lịch và Lữ hành',
    schoolId: 'DTU',
    schoolName: 'Đại học Duy Tân',
    examGroups: ['A00', 'C00', 'D01'],
    score: 19.5,
    tuitionFee: 30,
    demand: 4.1,
    salary: '12-22M',
    views: 5400,
    color: 'bg-red-100',
    icon: '✈️',
    duration: 4,
    students: 300,
    category: 'tourism',
    code: '7810103',
    description: 'Ngành học về quản trị, điều hành các hoạt động du lịch, thiết kế tour, chăm sóc khách hàng và phát triển các sản phẩm lữ hành.',
    suggestedJobs: ['Hướng dẫn viên du lịch', 'Điều hành tour', 'Quản lý khách sạn/resort', 'Chuyên viên tổ chức sự kiện']
  }
]
